### ISSUE TITLE
Lib does not export standard number implementation

### ISSUE THREAD

**Issue by macdja38** [pnicorelli/nodejs-chinese-remainder#5]
https://github.com/pnicorelli/nodejs-chinese-remainder/blob/master/index.js

The first export is overwritten by the second export.

You can wrap them in a object then export that object.

`module.exports = { crt, crt_bignum }`

**Comment by galElmalah** [comment]
@macdja38 
Advent of code lol?

**Comment by pnicorelli** [comment]
thanks for the contrib, I merged the code and published a 0.0.7 version on npm
